# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2019

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'APIProjectClasses/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PowerShell@2
  displayName: 'Executing Cypress Tests'
  inputs:
    targetType: 'inline'
    script: 'mvn clean test -DpetIDPOST="20" -DcatagNamePOST="catagName" -DtestUserNamePOST="testUserName" -DphotoUrlsPOST="photoUrls" -DtagNamePOST="tagName" -DpetIDGET="20" -DpetIDPUT="20" -DcatagNamePUT="catagName" -DtestUserNamePUT="testUserName" -DphotoUrlsPUT="photoUrls" -DtagNamePUT="tagName" -DpetIDDelete="20" -Dclassname="TestSuitePackage.TestSuiteREST"'
    failOnStderr: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    mergeTestResults: true
    continueOnError: true
    publishRunAttachments: true
    failTaskOnFailedTests: true

- task: CopyFiles@2
  displayName: 'Copy Report Files'
  condition: always()
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    continueOnError: true


- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'TestReports'
    continueOnError: true
    publishRunAttachments: true
